String html() {
  String html;
  
  html+="<!DOCTYPE html>";
  html+="<html>";
    html+="<head>";
      html+="<meta charset=\"UTF-8\">";
      html+="<title>Налаштування</title>";
      html+="<meta name=\"viewport\"content=\"width=device-width,initial-scale=1\">";
      html+="<link rel=\"apple-touch-icon\"sizes=\"180x180\"href=\"https://alarm-map.sdl.pp.ua/firmware/premium/icon/apple-touch-icon.png\">";
      html+="<link rel=\"icon\"type=\"image/png\"sizes=\"32x32\"href=\"https://alarm-map.sdl.pp.ua/firmware/premium/icon/favicon-32x32.png\">";
      html+="<link rel=\"icon\"type=\"image/png\"sizes=\"16x16\"href=\"https://alarm-map.sdl.pp.ua/firmware/premium/icon/favicon-16x16.png\">";
      html+="<link rel=\"manifest\"href=\"https://alarm-map.sdl.pp.ua/firmware/premium/icon/site.webmanifest\">";
    html+="</head>";
    html+="<style>";
      html+="html{";
        html+="font-family:Arial,Helvetica,sans-serif;";
        html+="display:inline-block;";
        html+="text-align:center;";
      html+="}";
      html+="body{";
        html+="margin:0;";
      html+="}";
      html+="h1{";
        html+="font-size:1.8rem;";
        html+="margin-bottom:0;";
      html+="}";
      html+="p{";
        html+="font-size:1.4rem;";
      html+="}";
      html+=".topnav{";
        html+="overflow:hidden;";
      html+="}";
      html+=".content{";
        html+="padding-top:5%;";
      html+="}";
      html+=".card-grid{";
        html+="padding-right:5%;";
        html+="padding-bottom:5%;";
        html+="padding-left:5%;";
        html+="max-width:800px;";
        html+="margin:0 auto;";
        html+="display:grid;";
        html+="grid-gap:2rem;";
        html+="grid-template-columns:repeat(auto-fit,minmax(300px,1fr));";
      html+="}";
      html+=".card,.topnav{";
        html+="box-shadow:2px 2px 12px 1px rgba(140,140,140,.5);";
      html+="}";
      html+="input[type=submit],.submit-button{";
        html+="border:none;";
        html+="padding:15px 15px;";
        html+="text-align:center;";
        html+="text-decoration:none;";
        html+="display:inline-block;";
        html+="font-size:16px;";
        html+="width:100px;";
        html+="margin-right:10px;";
        html+="border-radius:4px;";
        html+="transition-duration:0.4s;";
      html+="}";
      html+="input[type=text],input[type=number],input[type=time],select{";
        html+="width:80%;";
        html+="padding:12px 20px;";
        html+="margin:18px;";
        html+="display:inline-block;";
        html+="border-radius:4px;";
        html+="box-sizing:border-box;";
      html+="}";
      html+=".group{";
        html+="position:relative;";
        html+="width:80%;";
        html+="display:inline-block;";
      html+="}";
      html+=".group input[type=text],.group input[type=number],.group input[type=time],.group select{";
        html+="display:block;";
        html+="width:100%;";
        html+="margin:18px 0 18px 0;";
      html+="}";
      html+=".group input:focus{";
        html+="outline:none;";
      html+="}";
      html+=".group label{";
        html+="text-align:left;";
        html+="margin-left:12px;";
        html+="width:inherit;";
        html+="color:gray;";
        html+="font-size:14px;";
        html+="position:absolute;";
        html+="pointer-events:none;";
        html+="left:5px;";
        html+="top:30px;";
        html+="transition:0.2s ease all;";
        html+="-moz-transition:0.2s ease all;";
        html+="-webkit-transition:0.2s ease all;";
        html+="white-space:nowrap;";
        html+="overflow:hidden;";
        html+="text-overflow:ellipsis;";
      html+="}";
      html+=".group input:focus~label,";
      html+=".group input:not(:placeholder-shown)~label,";
      html+=".group select~label";
      html+="{";
        html+="margin:0;";
        html+="top:0px;";
      html+="}";
      html+=".label-box label";
      html+="{";
        html+="top:-18px !important;";
      html+="}";
      html+=".input-box{";
        html+="text-align:left;";
        html+="width:80%;";
        html+="padding:12px 20px;";
        html+="margin:18px;";
        html+="display:inline-block;";
        html+="border-radius:4px;";
        html+="box-sizing:border-box;";
      html+="}";
      html+=".input-box .input-box{";
        html+="margin-left:0;";
        html+="margin-right:0;";
      html+="}";
      html+="ol,ul{";
        html+="width:80%;";
        html+="text-align:left;";
        html+="display:inline-block;";
        html+="margin-top:0;";
      html+="}";
      html+=".logo{";
        html+="position:fixed;";
        html+="bottom:0;";
        html+="right:0;";
        html+="margin:10px;";
      html+="}";
      html+="@media(prefers-color-scheme:light){";
        html+="h1{";
          html+="color:white;";
        html+="}";
        html+="h1,h4,a{";
          html+="color:#034078;";
        html+="}";
        html+=".topnav{";
          html+="background:rgb(0,87,184);";
          html+="background:-moz-linear-gradient(90deg,rgba(0,87,184,1) 0%,rgba(255,215,0,1) 100%);";
          html+="background:-webkit-linear-gradient(90deg,rgba(0,87,184,1) 0%,rgba(255,215,0,1) 100%);";
          html+="background:linear-gradient(90deg,rgba(0,87,184,1) 0%,rgba(255,215,0,1) 100%);";
          html+="filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=\"#0057b8\",endColorstr=\"#ffd700\",GradientType=1);";
        html+="}";
        html+="input[type=submit],.submit-button{";
          html+="color:#FEFCFB;";
          html+="background-color:#034078;";
        html+="}";
        html+="input[type=submit]:hover,.submit-button:hover{";
          html+="background-color:#002f59;";
        html+="}";
        html+="input[type=text],input[type=number],input[type=time],select,.input-box{";
          html+="border:1px solid #ccc;";
        html+="}";  
        html+=".group input:focus~label,";
        html+=".group input:not(:placeholder-shown)~label,";
        html+=".group select~label";
        html+="{";
          html+="color:black;";
        html+="}";
      html+="}";
      html+="@media(prefers-color-scheme:dark){";
        html+="body{";
          html+="background-color:#17191a;";
        html+="}";
        html+="h1,h1 label,a{";
          html+="color:#7ebeef";
        html+="}";
        html+="label,h4,ul,ol,";
        html+=".group input:focus~label,";
        html+=".group input:not(:placeholder-shown)~label,";
        html+=".group select~label";
        html+="{"; 
          html+="color:white;";
        html+="}";
        html+=".topnav{";
          html+="background:rgb(0,44,93);";
          html+="background:-moz-linear-gradient(90deg,rgba(0,44,93,1) 0%,rgba(142,119,1,1)100%);";
          html+="background:-webkit-linear-gradient(90deg,rgba(0,44,93,1) 0%,rgba(142,119,1,1)100%);";
          html+="background:linear-gradient(90deg,rgba(0,44,93,1) 0%,rgba(142,119,1,1)100%);";
          html+="filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=\"#002c5d\",endColorstr=\"#8e7701\",GradientType=1);";
        html+="}";
        html+="input[type=text],input[type=number],input[type=time],select,.input-box{";
          html+="border:1px solid gray;";
          html+="color:white;";
          html+="background-color:#3b3b3b;";
        html+="}";
        html+=".input-box{";
          html+="background:none;";
        html+="}";
        html+="input[type=submit],.submit-button{";
          html+="color:white;";
          html+="background-color:#02305b;";
        html+="}";
        html+="input[type=submit]:hover,.submit-button:hover{";
          html+="background-color:#012241;";
        html+="}";
      html+="}";
    html+="</style>";
    html+="<body>";
      html+="<div class=\"topnav\">";
        html+="<h1 style=\"color:white;margin:20px;\">Налаштування карти повітряних тривог</h1>";
      html+="</div>";
      html+="<div class=\"content\">";
        html+="<form action=\"/\"method=\"POST\">";
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1>WiFi</h1>";
  if (!WiFiConnected()) {
              html+="<select onchange=\"ssid.value = this.value\">";
              html+="<option value=\"\">Виберіть зі списку або введіть вручну</option>";
                for (int i = 0; i < networksCount; ++i) html+="<option value=\"" + WiFi.SSID(i) + "\"" + String(ssid == WiFi.SSID(i) ? " selected" : EMPTY) + ">" + WiFi.SSID(i) + "</option>";
              html+="</select>";
  }
              html+="<div class=\"group\">";
                html+="<input type=\"text\"name=\"ssid\"id=\"ssid\"value=\"" + ssid + "\"required>";
                html+="<label>SSID</label>";
              html+="</div>";
              html+="<div class=\"group\">";
                html+="<input type=\"text\"name=\"pass\"value=\"" + password + "\"minlength=\"8\">";
                html+="<label>Пароль</label>";
              html+="</div>";
  if (WiFiConnected()) {
              html+="<div class=\"group\">";
                html+="<input type=\"number\"name=\"wifi-connect-time\"value=\"" + String(wifiConnectTime / 1000) + "\"min=\"5\"required>";
                html+="<label>Час очікування підключення до мережі (в секундах)</label>";
              html+="</div>";
  }
            html+="</div>";
          html+="</div>";
  if (WiFiConnected()) {
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1>Ключ доступу</h1>";
              html+="<div class=\"group\">";
                html+="<input type=\"text\"placeholder=\"\"name=\"acces-key\" value=\"" + accesKey + "\" minlength=\"15\" maxlength=\"15\" required>";
                html+="<label>Ключ доступу</label>";
              html+="</div>";
              html+="<ul>";
  if (accesKey.length() > 0) {
    if (validKey) html+="<li>Пристрій доступний! " + checkKeyMessage + "</li>";
    else html+="<li>Пристрій заблоковано! " + checkKeyMessage + "</li>";
  }
                html+="<li>Щоб придбати ключ доступу зверніться в <a href=\"https://t.me/alarm_map_support\"target=\"_blank\">службу підтримки SDL Alarm Map - @alarm_map_support</a>.</li>";
              html+="</ul>";
            html+="</div>";
          html+="</div>";
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1>Бот</h1>";
              html+="<div class=\"group\">";
                html+="<input type=\"text\"id=\"token\"name=\"token\"value=\"" + botToken + "\"minlength=\"46\"maxlength=\"46\"required>";
                html+="<label>Токен Telegram бота</label>";
              html+="</div>";
              html+="<ol>";
                html+="<li>Введіть у полі пошуку <a href=\"https://t.me/BotFather\"target=\"_blank\">@BotFather</a> і виберіть бот. У офіційного бота Telegram стоятиме синій знак підтвердження, біля імені у вигляді галочки;</li>";
                html+="<li>Натисніть «Запустити» для активації бота BotFather;</li>";
                html+="<li>У відповідь ви отримаєте список команд з управління ботом;</li>";
                html+="<li>Виберіть або надрукуйте та надішліть команду /newbot;</li>";
                html+="<li>Дайте ім'я боту — ви побачите це ім'я під час спілкування з ботом. І нікнейм бота — за ним можна буде знайти бота в Telegram. Нікнейм має бути унікальним, не повторювати існуючі в базі та закінчуватися словом «bot»;</li>";
                html+="<li>Після того як ви оберете відповідне ім'я бот буде створено. Ви отримаєте повідомлення з посиланням на бота t.me/нікнейм_бота. Для підключення бота вам знадобиться токен. Скопіюйте значення токена та вставте його в поле вище.</li>";
              html+="</ol>";
              html+="<button type=\"button\" onclick=\"getTelegramID()\" class=\"input-box\" id=\"get-telegram-id\" style=\"text-align: center;\">Визначити Telegram ID</button>";
              html+="<div class=\"group\">";
                html+="<input type=\"number\" id=\"chat-id\" name=\"chat-id\" placeholder=\"Telegram ID\" value=\"" + chatID + "\" required>";
                html+="<label>Telegram ID</label>";
              html+="</div>";
            html+="</div>";
          html+="</div>";
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1>Тривоги</h1>";
              html+="<select id=\"alarms-source\"name=\"alarms-source\"onchange=\"if(this.value=='2'){document.getElementById('alarms-token').style.display='inline-block';document.getElementById('alarms-interval').setAttribute('min',5);}else{document.getElementById('alarms-token').style.display='none';document.getElementById('alarms-interval').setAttribute('min',10);}\">";
                html+="<option value=\"0\"" + String(alarmsSource == 0 ? " selected" : EMPTY) + ">АПІ Клименко Вадима - vadimklimenko.com</option>";
                html+="<option value=\"1\"" + String(alarmsSource == 1 ? " selected" : EMPTY) + ">Ubilling - ubilling.net.ua/aerialalerts</option>";
                html+="<option value=\"2\"" + String(alarmsSource == 2 ? " selected" : EMPTY) + ">Офіційне АПІ - map.ukrainealarm.com (необхідний токен)</option>";
                html+="<option value=\"3\"" + String(alarmsSource == 3 ? " selected" : EMPTY) + ">Сервер даних JAAM - alerts.net.ua</option>";
              html+="</select><br>";
              html+="<div class=\"group\"id=\"alarms-token\"" + String(alarmsSource == 2 ? EMPTY : "style=\"display: none;\"") + ">";
                html+="<input type=\"text\"name=\"alarms-token\"minlength=\"41\"maxlength=\"41\"value=\"" + alarmsToken + "\">";
                html+="<label>Токен доступу до АПІ</label>";
              html+="</div>";
              html+="<div class=\"group\">";
                html+="<input type=\"number\"name=\"alarms-interval\"id=\"alarms-interval\"min=\"" + String(alarmsSource == 2 ? "5" : "10") + "\"value=\"" + String(alarmsInterval / 1000) + "\" required>";
                html+="<label>Інтервал між оновленням даних (в секундах)</label>";
              html+="</div>";
              html+="<select name=\"home-city\">";
                html+="<option value=\"\">Домашній регіон</option>";
                html+="<option value=\"м. Київ\"" + String(homeCity == "м. Київ" ? " selected" : EMPTY) + ">м. Київ</option>";
                html+="<option value=\"АР Крим\"" + String(homeCity == "АР Крим" ? " selected" : EMPTY) + ">АР Крим</option>";
                html+="<option value=\"Вінницька область\"" + String(homeCity == "Вінницька область" ? " selected" : EMPTY) + ">Вінницька область</option>";
                html+="<option value=\"Волиньська область\"" + String(homeCity == "Волиньська область" ? " selected" : EMPTY) + ">Волиньська область</option>";
                html+="<option value=\"Дніпропетровська область\"" + String(homeCity == "Дніпропетровська область" ? " selected" : EMPTY) + ">Дніпропетровська область</option>";
                html+="<option value=\"Донецька область\"" + String(homeCity == "Донецька область" ? " selected" : EMPTY) + ">Донецька область</option>";
                html+="<option value=\"Житомирська область\"" + String(homeCity == "Житомирська область" ? " selected" : EMPTY) + ">Житомирська область</option>";
                html+="<option value=\"Закарпатська область\"" + String(homeCity == "Закарпатська область" ? " selected" : EMPTY) + ">Закарпатська область</option>";
                html+="<option value=\"Запорізька область\"" + String(homeCity == "Запорізька область" ? " selected" : EMPTY) + ">Запорізька область</option>";
                html+="<option value=\"Івано-Франківська область\"" + String(homeCity == "Івано-Франківська область" ? " selected" : EMPTY) + ">Івано-Франківська область</option>";
                html+="<option value=\"Київська область\"" + String(homeCity == "Київська область" ? " selected" : EMPTY) + ">Київська область</option>";
                html+="<option value=\"Кіровоградська область\"" + String(homeCity == "Кіровоградська область" ? " selected" : EMPTY) + ">Кіровоградська область</option>";
                html+="<option value=\"Луганська область\"" + String(homeCity == "Луганська область" ? " selected" : EMPTY) + ">Луганська область</option>";
                html+="<option value=\"Львівська область\"" + String(homeCity == "Львівська область" ? " selected" : EMPTY) + ">Львівська область</option>";
                html+="<option value=\"Миколаївська область\"" + String(homeCity == "Миколаївська область" ? " selected" : EMPTY) + ">Миколаївська область</option>";
                html+="<option value=\"Одеська область\"" + String(homeCity == "Одеська область" ? " selected" : EMPTY) + ">Одеська область</option>";
                html+="<option value=\"Полтавська область\"" + String(homeCity == "Полтавська область" ? " selected" : EMPTY) + ">Полтавська область</option>";
                html+="<option value=\"Рівненська область\"" + String(homeCity == "Рівненська область" ? " selected" : EMPTY) + ">Рівненська область</option>";
                html+="<option value=\"Сумська область\"" + String(homeCity == "Сумська область" ? " selected" : EMPTY) + ">Сумська область</option>";
                html+="<option value=\"Тернопільська область\"" + String(homeCity == "Тернопільська область" ? " selected" : EMPTY) + ">Тернопільська область</option>";
                html+="<option value=\"Харківська область\"" + String(homeCity == "Харківська область" ? " selected" : EMPTY) + ">Харківська область</option>";
                html+="<option value=\"Херсонська область\"" + String(homeCity == "Херсонська область" ? " selected" : EMPTY) + ">Херсонська область</option>";
                html+="<option value=\"Хмельницька область\"" + String(homeCity == "Хмельницька область" ? " selected" : EMPTY) + ">Хмельницька область</option>";
                html+="<option value=\"Черкаська область\"" + String(homeCity == "Черкаська область" ? " selected" : EMPTY) + ">Черкаська область</option>";
                html+="<option value=\"Чернівецька область\"" + String(homeCity == "Чернівецька область" ? " selected" : EMPTY) + ">Чернівецька область</option>";
                html+="<option value=\"Чернігівська область\"" + String(homeCity == "Чернігівська область" ? " selected" : EMPTY) + ">Чернігівська область</option>";
              html+="</select>";
              html+="<div class=\"input-box\">";
                html+="<input type=\"checkbox\"id=\"integration-checkbox\"onchange=\"toggleCheckbox(this,document.getElementById('integration'));toggleDiv(this,'',document.getElementById('integration-settings'))\"" + String(integrationPresent ? "checked" : EMPTY) + "><label for=\"integration-checkbox\">Інтеграція додаткового модулю</label><br>";
                html+="<input type=\"number\"id=\"integration\"name=\"integration\"value=\"" + String(integrationPresent) + "\"style=\"display:none;\">";
                html+="<div id=\"integration-settings\"" + String(!integrationPresent ? " style=\"display:none;\"" : EMPTY) + ">";
                  html+="<br>";
                  html+="<div class=\"group\">";
                    html+="<input type=\"number\"name=\"integration-pin\"min=\"0\"value=\"" + String(integrationPin) + "\" required>";
                    html+="<label>Пін</label>";
                  html+="</div>";
                  html+="<div class=\"group\">";
                    html+="<select name=\"integration-high\">";
                      html+="<option value=\"1\"" + String(integrationHigh ? " selected" : EMPTY) + ">HIGH</option>";
                      html+="<option value=\"0\"" + String(!integrationHigh ? " selected" : EMPTY) + ">LOW</option>";
                    html+="</select>";
                    html+="<label>Стан піну при тривозі в домашньому регіоні</label>";
                  html+="</div>";
                html+="</div>";
              html+="</div>";
            html+="</div>";
          html+="</div>";
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1>Світлодіодна стрічка</h1>";
              html+="<div class=\"group\">";
                html+="<input type=\"number\"name=\"led-pin\"min=\"0\"value=\"" + String(stripPin) + "\"required>";
                html+="<label>Пін</label>";
              html+="</div>";
              html+="<select name=\"led-type\">";
                html+="<option value=\"grb\"" + String(stripType == "grb" ? " selected" : EMPTY) + ">GRB (найпоширеніший)</option>";
                html+="<option value=\"rgb\"" + String(stripType == "rgb" ? " selected" : EMPTY) + ">RGB</option>";
                html+="<option value=\"rbg\"" + String(stripType == "rbg" ? " selected" : EMPTY) + ">RBG</option>";
                html+="<option value=\"gbr\"" + String(stripType == "gbr" ? " selected" : EMPTY) + ">GBR</option>";
                html+="<option value=\"brg\"" + String(stripType == "brg" ? " selected" : EMPTY) + ">BRG</option>";
                html+="<option value=\"bgr\"" + String(stripType == "bgr" ? " selected" : EMPTY) + ">BGR</option>";
              html+="</select><br>";
              html+="<select name=\"states-order\">";
                html+="<option value=\"0\"" + String(statesOrder == 0 ? " selected" : EMPTY) + ">Закарпатська область - Чернівецька область (стандартне)</option>";
                html+="<option value=\"1\"" + String(statesOrder == 1 ? " selected" : EMPTY) + ">Одеська область - АР Крим (плата JAAM)</option>";
              html+="</select><br>";
              html+="<select name=\"kyiv-mode\">";
                html+="<option value=\"0\"" + String(kyivMode == 0 ? " selected" : EMPTY) + ">Київська область (1 діод)</option>";
                html+="<option value=\"1\"" + String(kyivMode == 1 ? " selected" : EMPTY) + ">Київ (1 діод)</option>";
                html+="<option value=\"2\"" + String(kyivMode == 2 ? " selected" : EMPTY) + ">Київська область + Київ (2 діода)</option>";
              html+="</select><br>";
              html+="<div class=\"input-box\">";
                html+="<input type=\"checkbox\"id=\"green-states-checkbox\"onchange=\"toggleCheckbox(this,document.getElementById('green-states'))\"" + String(greenStates?"checked" : EMPTY) +"><label for=\"green-states-checkbox\">Зелені області без тривог</label><br>";
                html+="<input type=\"number\"id=\"green-states\"name=\"green-states\"value=\"" + String(greenStates) + "\"style=\"display:none;\">";
              html+="</div>";
              html+="<div class=\"input-box\">";
                html+="<div class=\"group\">";
                  html+="<select name=\"autobrightness-source\"id=\"autobrightness-source\"onchange=\"document.getElementById('time-settings').style.display=this.value=='0'?'block':'none';document.getElementById('photoresistor-settings').style.display=this.value=='1'?'block':'none';\">";
                    html+="<option value=\"0\"" + String(autoBrightnessSource == 0 ? " selected" : EMPTY) + ">Час</option>";
                    html+="<option value=\"1\"" + String(autoBrightnessSource == 1 ? " selected" : EMPTY) + ">Фоторезистор</option>";
                  html+="</select>";
                  html+="<label>Джерело автояскравості</label>";
                html+="</div>";
                html+="<div id=\"time-settings\"" + String(autoBrightnessSource != 0 ? " style=\"display:none;\"" : EMPTY) + ">";
                  html+="<div class=\"group\">";
                    html+="<input type=\"time\"name=\"day-time\" value=\"" + String(dayHour < 10 ? "0" : EMPTY) + String(dayHour) + ":" + String(dayMinute < 10 ? "0" : EMPTY) + String(dayMinute) + "\">";
                    html+="<label>Активація денної яскравості о</label>";
                  html+="</div>";
                  html+="<div class=\"group input-box label-box\">";
                    html+="<input type=\"range\"name=\"day-brightness\"value=\"" + String(dayBrightness) + "\"min=\"1\"max=\"100\"oninput=\"document.getElementById(\'day-time-span\').innerHTML = this.value + '%'\">";
                    html+="<span id=\"day-time-span\">" + String(dayBrightness) + "%</span>";
                    html+="<label>Денна яскравість</label>";
                  html+="</div>";
                  html+="<div class=\"group\">";
                    html+="<input type=\"time\"name=\"night-time\" value=\"" + String(nightHour < 10 ? "0" : EMPTY) + String(nightHour) + ":" + String(nightMinute < 10 ? "0" : EMPTY) + String(nightMinute) + "\">";
                    html+="<label>Активація нічної яскравості о</label>";
                  html+="</div>";
                  html+="<div class=\"group input-box label-box\">";
                    html+="<input type=\"range\"name=\"night-brightness\"value=\"" + String(nightBrightness) + "\"min=\"1\"max=\"100\"oninput=\"document.getElementById(\'night-time-span\').innerHTML = this.value + '%'\">";
                    html+="<span id=\"night-time-span\">" + String(nightBrightness) + "%</span>";
                    html+="<label>Нічна яскравість</label>";
                  html+="</div>";
                html+="</div>";
                html+="<div id=\"photoresistor-settings\"" + String(autoBrightnessSource != 1 ? " style=\"display:none;\"" : EMPTY) + ">";
                  html+="<div class=\"group\">";
                    html+="<input type=\"number\"name=\"photoresistor-pin\"min=\"0\"value=\"" + (photoresistorPin > 0 ? String(photoresistorPin) : EMPTY) + "\">";
                    html+="<label>Пін</label>";
                  html+="</div>";
  if (autoBrightnessSource == 1) {
                  html+="<div class=\"input-box\">";
                    html+="Поточне освітлення: <span id=\"light\">" + String(getPhotoresistorValue()) + "</span>";
                  html+="</div>";
                  html+="<div class=\"group\">";
                    html+="<input type=\"number\"name=\"light-max\"min=\"0\"value=\"" + (lightMax >= 0 ? String(lightMax) : EMPTY) + "\">";
                    html+="<label>Максимальне освітлення</label>";
                  html+="</div>";
                  html+="<div class=\"group\">";
                    html+="<input type=\"number\"name=\"light-min\"min=\"0\"value=\"" + (lightMin >= 0 ? String(lightMin) : EMPTY) + "\">";
                    html+="<label>Мінімальне освітлення</label>";
                  html+="</div>";
  }
                html+="</div>";
              html+="</div>";
              html+="<div class=\"input-box\">";
                html+="<input type=\"checkbox\"id=\"silence-minute-checkbox\"onchange=\"toggleCheckbox(this,document.getElementById('silence-minute'))\"" + String(silenceMinuteEnabled ?"checked" : EMPTY) +"><label for=\"silence-minute-checkbox\">Відображення прапору під час хвилини мовчання о 9:00</label><br>";
                html+="<input type=\"number\"id=\"silence-minute\"name=\"silence-minute\"value=\"" + String(silenceMinuteEnabled) + "\"style=\"display:none;\">";
              html+="</div>";
            html+="</div>";
          html+="</div>";
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1 id=\"sound-title\"" + String(soundSource != 0 ? EMPTY : " style=\"margin-bottom: 0.67em;\"") + ">";
                html+="<input type=\"checkbox\"id=\"sound-checkbox\"onchange=\"toggleCheckbox(this,document.getElementById('sound'));toggleDiv(this,document.getElementById('sound-title'),document.getElementById('sound-settings'))\"" + String(soundSource != 0 ? "checked" : EMPTY) + ">";
                html+="<label for=\"sound-checkbox\">Звук</label>";
              html+="</h1>";
              html+="<input type=\"number\"id=\"sound\"name=\"sound\"value=\"" + String(soundSource != 0) + "\"style=\"display:none;\">";

                html+="<div id=\"sound-settings\"" + String(soundSource == 0 ? " style=\"display:none;\"" : EMPTY) + ">";
                  html+="<select name=\"sound-source\"id=\"sound-source\"onchange=\"document.getElementById('buzzer-settings').style.display=this.value=='1'?'block':'none';document.getElementById('speaker-settings').style.display=this.value=='2'?'block':'none';\">";
                    html+="<option value=\"1\"" + String(soundSource == 1 ? " selected" : EMPTY) + ">Бузер</option>";
                    html+="<option value=\"2\"" + String(soundSource == 2 ? " selected" : EMPTY) + ">Динамік</option>";
                  html+="</select>";

                  html+="<div id=\"buzzer-settings\"" + String((soundSource != 1 || soundSource != 0) ? " style=\"display:none;\"" : EMPTY) + ">";
                    html+="<div class=\"group\">";
                      html+="<input type=\"number\"name=\"buzzer-pin\"min=\"0\"value=\"" + String(buzzerPin) + "\">";
                      html+="<label>Пін</label>";
                    html+="</div>";
                    html+="<div class=\"group\">";
                      html+="<input type=\"number\"name=\"buzzer-interval\"min=\"0\"max=\"60\"value=\"" + String(buzzerInterval / 1000) + "\">";
                      html+="<label>Тривалість звукового оповіщення (в секундах)</label>";
                    html+="</div>";
                  html+="</div>";

                  html+="<div id=\"speaker-settings\"" + String(soundSource != 2 ? " style=\"display:none;\"" : EMPTY) + ">";
                    html+="<div class=\"group input-box label-box\">";
                      html+="<input type=\"range\"name=\"speaker-volume\"value=\"" + String(speakerVolume) + "\"min=\"1\"max=\"100\"oninput=\"document.getElementById(\'speaker-volume-span\').innerHTML = this.value + '%'\">";
                      html+="<span id=\"speaker-volume-span\">" + String(speakerVolume) + "%</span>";
                      html+="<label>Гучність</label>";
                    html+="</div>";
                  html+="</div>";

                html+="</div>";
            html+="</div>";
          html+="</div>";
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1 id=\"display-title\"" + String(displayPresent ? EMPTY : " style=\"margin-bottom: 0.67em;\"") + ">";
                html+="<input type=\"checkbox\"id=\"display-present-checkbox\"onchange=\"toggleDiv(this,document.getElementById('display-title'),document.getElementById('display-settings'));toggleCheckbox(this,document.getElementById('display-present'))\"" + String(displayPresent ? "checked" : EMPTY) +">";
                html+="<label for=\"display-present-checkbox\">Дисплей</label>";
              html+="</h1>";
              html+="<input type=\"number\"id=\"display-present\"name=\"display-present\"value=\"" + String(displayPresent) + "\"style=\"display:none;\">";
  String displayTitle = "oled-" + displayCommunication + "-" + String(displayWidth) + "x" + String(displayHeight) + "-ssd1306";
              html+="<div id=\"display-settings\"" + String(displayPresent ? EMPTY : " style=\"display:none;\"") + ">";
                html+="<select name=\"display-type\">";
                  html+="<option value=\"oled-i2c-128x32-ssd1306\"" + String(displayTitle == "oled-i2c-128x32-ssd1306" ? " selected" : EMPTY) + ">OLED I2C 128x32 SSD1306</option>";
                  html+="<option value=\"oled-i2c-128x64-ssd1306\"" + String(displayTitle == "oled-i2c-128x64-ssd1306" ? " selected" : EMPTY) + ">OLED I2C 128x64 SSD1306</option>";
                  html+="<option value=\"oled-spi-128x32-ssd1306\"" + String(displayTitle == "oled-spi-128x32-ssd1306" ? " selected" : EMPTY) + ">OLED SPI 128x32 SSD1306</option>";
                  html+="<option value=\"oled-spi-128x64-ssd1306\"" + String(displayTitle == "oled-spi-128x64-ssd1306" ? " selected" : EMPTY) + ">OLED SPI 128x64 SSD1306</option>";
                html+="</select><br>";
                html+="<div class=\"input-box\">";
                  html+="<input type=\"checkbox\"id=\"flip-display-checkbox\"onchange=\"toggleCheckbox(this,document.getElementById('flip-display'))\"" + String(displayFlip ? "checked" : EMPTY) +"><label for=\"flip-display-checkbox\">Повернути на 180°</label><br>";
                  html+="<input type=\"number\"id=\"flip-display\"name=\"flip-display\"value=\"" + String(displayFlip) + "\"style=\"display:none;\">";
                html+="</div>";
                html+="<div class=\"input-box\">";
                  html+="<input type=\"checkbox\"id=\"display-mode-0\"onchange=\"generateDisplayModes()\"" + String(displayModes[TIME_MODE] ? "checked" : EMPTY) + "><label for=\"display-mode-0\">Час</label><br>";
                  html+="<input type=\"checkbox\"id=\"display-mode-1\"onchange=\"generateDisplayModes()\"" + String(displayModes[DATE_MODE] ? "checked" : EMPTY) + "><label for=\"display-mode-1\">Дата</label><br>";
                  html+="<input type=\"checkbox\"id=\"display-mode-2\"onchange=\"generateDisplayModes(); document.getElementById('temperature-present-checkbox')[this.checked ? 'setAttribute' : 'removeAttribute']('required', 'true');\"" + String(displayModes[CONDITIONS_MODE] ? "checked" : EMPTY) + "><label for=\"display-mode-2\">Температура і вологість (вимагає налаштування DHT)</label><br>";
                  html+="<input type=\"checkbox\"id=\"display-mode-3\"onchange=\"generateDisplayModes(); toggleDiv(this, '', document.getElementById('weather-settings'))\"" + String(displayModes[WEATHER_MODE] ? "checked" : EMPTY) + "><label for=\"display-mode-3\">Погода</label><br>";
                  html+="<div id=\"weather-settings\"" + String(!displayModes[WEATHER_MODE] ? " style=\"display:none;\"" : EMPTY) + ">";
                    html+="<br>";
                    html+="<div class=\"group\">";
                      html+="<input type=\"text\"name=\"weather-token\"value=\"" + weatherToken + "\"minlength=\"32\"maxlength=\"32\">";
                      html+="<label>Ключ Open Weather Map</label>";
                    html+="</div>";
                    html+="<ol>";
                      html+="<li>Відвідайте сайт <a href=\"https://openweathermap.org/\"target=\"_blank\">OpenWeatherMap</a> і клацніть \"Sign Up\", щоб створити новий обліковий запис, заповнивши необхідну інформацію. Перевірте свою електронну пошту, вказану при реєстрації, для отримання листа від OpenWeatherMap;</li>";
                      html+="<li>Відкрийте лист від OpenWeatherMap та перейдіть за посиланням для верифікації електронної пошти. Після успішної верифікації отримаєте другий лист із зазначеним токеном API. Вставте цей токен у відповідне поле вище.</li>";
                    html+="</ol>";
                    html+="<div class=\"group\">";
                      html+="<input type=\"number\"id=\"home-city-id\"name=\"home-city-id\"value=\"" + (homeCityId > 0 ? String(homeCityId) : EMPTY) + "\">";
                      html+="<label>ID населеного пункту</label>";
                    html+="</div>";
                    html+="<ol>";
                      html+="<li>Відвідайте сайт <a href=\"https://openweathermap.org/\" target=\"_blank\">OpenWeatherMap</a> і введіть назву вашого населеного пункту у поле пошуку і натисніть кнопку \"Пошук\";</li>";
                      html+="<li>Знайдіть ваше місто в результатах пошуку і натисніть на його назву. ID населеного пункту можна знайти в адресному рядку вашого веб-браузера.</li>";
                    html+="</ol>";
                  html+="</div>";
                  html+="<input type=\"checkbox\"id=\"display-mode-4\"onchange=\"generateDisplayModes()\"" + String(displayModes[ALARM_INFO_MODE] ? "checked" : EMPTY) + "><label for=\"display-mode-4\">Інформація про тривогу</label><br>";
                  html+="<input type=\"checkbox\"id=\"display-mode-5\"onchange=\"generateDisplayModes()\"" + String(displayModes[WAR_MODE] ? "checked" : EMPTY) + "><label for=\"display-mode-5\">Дані про війну</label><br>";
                  html+="<input type=\"checkbox\"id=\"display-mode-6\"onchange=\"generateDisplayModes()\"" + String(displayModes[CURRENCY_MODE] ? "checked" : EMPTY) + "><label for=\"display-mode-6\">Курс валют</label><br>";
                  html+="<input type=\"text\"id=\"display-modes\"name=\"display-modes\" value=\"" + String(displayModes[0]) + String(displayModes[1]) + String(displayModes[2]) + String(displayModes[3]) + String(displayModes[4]) + String(displayModes[5]) + String(displayModes[6]) + "\" style=\"display:none;\">";
                html+="</div>";
                html+="<div class=\"group\">";
                  html+="<input type=\"number\"name=\"autoswitch-interval\"min=\"5\"max=\"60\"value=\"" + String(autoSwitchDisplayInterval / 1000) + "\"><br>";
                  html+="<label>Інтервал зміни режимів (в секундах)</label>";
                html+="</div>";
              html+="</div>";
            html+="</div>";
          html+="</div>";
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1 id=\"temperature-title\"" + String(temperaturePresent ? EMPTY : " style=\"margin-bottom:0.67em;\"") + ">";
                html+="<input type=\"checkbox\"id=\"temperature-present-checkbox\"onchange=\"toggleDiv(this,document.getElementById('temperature-title'),document.getElementById('temperature-settings'));toggleCheckbox(this,document.getElementById('temperature-present'));document.getElementById('sinric-temperature-id').style.display=this.checked?'inline-block':'none';\"" + String(temperaturePresent ? "checked" : EMPTY) + " " + String(displayModes[CONDITIONS_MODE] ? "required" : EMPTY) + ">";
                html+="<label for=\"temperature-present-checkbox\">DHT</label>";
              html+="</h1>";
              html+="<input type=\"number\"id=\"temperature-present\"name=\"temperature-present\"value=\"" + String(temperaturePresent) + "\"style=\"display:none;\">";
              html+="<div id=\"temperature-settings\"" + String(temperaturePresent ? EMPTY : " style=\"display: none;\"") + ">";
                html+="<div class=\"group\">";
                  html+="<input type=\"number\"name=\"temperature-pin\"value=\"" + (temperaturePin > 0 ? String(temperaturePin) : EMPTY) + "\"min=\"0\">";
                  html+="<label>Пін</label>";
                html+="</div>";
                html+="<select name=\"temperature-type\">";
                  html+="<option value=\"11\"" + String(temperatureType == 11 ? " selected" : EMPTY) + ">DHT11</option>";
                  html+="<option value=\"21\"" + String(temperatureType == 21 ? " selected" : EMPTY) + ">DHT21</option>";
                  html+="<option value=\"22\"" + String(temperatureType == 22 ? " selected" : EMPTY) + ">DHT22</option>";
                html+="</select><br>";
                html+="<div class=\"group\">";
                  html+="<input type=\"number\"name=\"temperature-offset\"value=\"" + String(temperatureOffset) + "\"min=\"-10\"max=\"10\">";
                  html+="<label>Відхилення температури (°C)</label>";
                html+="</div>";
              html+="</div>";
            html+="</div>";
          html+="</div>";
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1>NTP</h1>";
              html+="<div class=\"group\">";
                html+="<input type=\"text\"name=\"ntp-host\"value=\"" + ntpHost + "\"required>";
                html+="<label>NTP сервер</label>";
              html+="</div>";
              html+="<div class=\"group\">";
                html+="<input type=\"number\"name=\"utc\"value=\"" + (timeZone > 0 ? String(timeZone) : EMPTY) + "\"min=\"-12\"max=\"14\"required>";
                html+="<label id=\"utc\"></label>";
              html+="</div>";
            html+="</div>";
          html+="</div>";
          html+="<div class=\"card-grid\">";
            html+="<div class=\"card\">";
              html+="<h1 id=\"sinric-title\"" + String(!sinricKey.isEmpty() ? EMPTY : "style=\"margin-bottom:0.67em;\"") + ">";
                html+="<input type=\"checkbox\"id=\"sinric-present-checkbox\"onchange=\"toggleDiv(this,document.getElementById('sinric-title'),document.getElementById('sinric-settings'));toggleCheckbox(this,document.getElementById('sinric-present'))\"" + String(!sinricKey.isEmpty() ? "checked" : EMPTY) + ">";
                html+="<label for=\"sinric-present-checkbox\">Інтеграція з Sinric Pro</label>";
              html+="</h1>";
              html+="<input type=\"number\"id=\"sinric\"name=\"sinric\"value=\"" + String(!sinricKey.isEmpty()) + "\"style=\"display:none;\">";
              html+="<div id=\"sinric-settings\"" + String(sinricKey.isEmpty() ? "style=\"display:none;\"" : EMPTY) + ">";
                html+="<br>";
                html+="<div class=\"group\">";
                  html+="<input type=\"text\"name=\"sinric-app-key\"value=\"" + sinricKey + "\"minlength=\"36\"maxlength=\"36\">";
                  html+="<label>APP KEY</label>";
                html+="</div>";
                html+="<div class=\"group\">";
                  html+="<input type=\"text\"name=\"sinric-app-secret\"value=\"" + sinricSecret + "\"minlength=\"73\"maxlength=\"73\">";
                  html+="<label>APP SECRET</label>";
                html+="</div>";
                html+="<div class=\"group\">";
                 html+="<input type=\"text\"name=\"sinric-led-id\"value=\"" + sinricStripId + "\"minlength=\"24\"maxlength=\"24\">";
                 html+="<label>ID перемикача з можливістю регулювання яскравості (Switch with Dimming)</label>";
                html+="</div>";
                html+="<div class=\"group\"id=\"sinric-temperature-id\"" + String(!temperaturePresent ? "style=\"display:none;\"" : EMPTY) + ">";
                 html+="<input type=\"text\"name=\"sinric-temperature-id\"value=\"" + sinricTemperatureId + "\"minlength=\"24\"maxlength=\"24\">";
                 html+="<label>ID датчика температури (Temperature Sensor)</label>";
                html+="</div>";
              html+="</div>";
            html+="</div>";
          html+="</div>";
  }
          html+="<input type=\"submit\"value=\"Зберегти\">";
          html+="<button onclick=\"restart()\"class=\"submit-button\">Рестарт</button>";
          html+="<button onclick=\"resetSettings()\"class=\"submit-button\">Скинути</button><br>";
        html+="</form>";
      html+="</div>";
  String ip = WiFiConnected() ? WiFi.localIP().toString() : WiFi.softAPIP().toString();
      html+="<h4>IP: <a href=\"http://" + ip + "\">" + ip + "</a></h4>";
  if (WiFiConnected()) html+="<h4><a href=\"https://raw.githubusercontent.com/danio273/alarm-map/main/docs/manual.pdf\" target=\"_blank\">Інструкція</a></h4>";
      html+="<h4><a href=\"https://t.me/alarm_map_support\" target=\"_blank\">Допомога | Служба підтримки</a></h4>";
  if (WiFiConnected()) html+="<a href=\"https://t.me/alarm_map_premium\" target=\"_blank\"><img src=\"https://raw.githubusercontent.com/danio273/alarm-map/main/assets/images/logo.png\" alt=\"SDL Alarm Map Premium logo\" height=\"70px\" class=\"logo\"></a>";
      html+="<script>";
  if (WiFiConnected()) {
      html+="var inputElements=document.querySelectorAll('input');";
      html+="inputElements.forEach(function(input){";
        html+="input.placeholder='';";
      html+="});";
        html+="function toggleCheckbox(checkbox,input){";
          html+="input.value=checkbox.checked?1:0;";
        html+="}";
        html+="function toggleDiv(checkbox,h1,div){";
          html+="if(checkbox.checked){";
              html+="div.style.display='block';";
              html+="h1.style.marginBottom='0';";
          html+="}else{";
              html+="div.style.display='none';";
              html+="h1.style.marginBottom='0.67em';";
          html+="}";
        html+="}";
  if (autoBrightnessSource == 1) {
        html+="setInterval(function(){";
          html+="if (document.getElementById(\"autobrightness-source\").value == 1) {";
            html+="var xhttp = new XMLHttpRequest();";
            html+="xhttp.onreadystatechange = function() {";
              html+="if(this.readyState==4&&this.status==200) {";
                html+="document.getElementById(\"light\").innerText=this.responseText;";
              html+="}";
            html+="};";
            html+="xhttp.open(\"GET\",\"/light\",true);";
            html+="xhttp.send();";
          html+="}";
        html+="},2000);";
  }
        html+="function fetchData(apiUrl){";
          html+="return fetch(apiUrl)";
            html+=".then(response=>{";
              html+="if(!response.ok){";
                html+="let error;";
                html+="if(response.status===401){";
                  html+="error='недійсний токен або ключ';";
                html+="}else{";
                  html+="error=response.status+' '+response.statusText;";
                html+="}";
                html+="throw error;";
              html+="}";
              html+="return response.json();";
            html+="})";
            html+=".catch(error=>{";
              html+="throw error;";
            html+="});";
        html+="}";
        html+="function getTelegramID(){";
          html+="const button=document.getElementById('get-telegram-id');";
          html+="const tokenInput=document.getElementById('token');";
          html+="const telegramIDInput=document.getElementById('chat-id');";
          html+="if (tokenInput.value.length===46){";
            html+="let text='Для автоматичного визначення Telegram ID, натисніть кнопку \"РОЗПОЧАТИ\" або відправте команду \"/start\" у бота, створеного на попередньому кроці. Якщо вам потрібно використовувати бота в групі, додайте його до групи і виконайте ті самі кроки.\\nЯкщо ви вже виконали ці дії, натискайте \"ОК\".';";
            html+="if(confirm(text)==true){";
              html+="fetchData(`https://api.telegram.org/bot${tokenInput.value}/getUpdates`)";
                html+=".then(data=>{";
                  html+="let chatName;";
                  html+="if(data.result[0].message.chat.type=='private'){";
                    html+="chatName=data.result[0].message.chat.first_name;";
                  html+="}else if(data.result[0].message.chat.type=='supergroup'){";
                    html+="chatName=data.result[0].message.chat.title;";
                  html+="}";
                  html+="button.textContent=`Визначити Telegram ID (${chatName})`;";
                  html+="telegramIDInput.value=data.result[0].message.chat.id;";
                html+="})";
                html+=".catch(error=>{";
                  html+="if(error == \"TypeError: Cannot read properties of undefined (reading 'message')\"){";
                    html+="alert('Повідомлення відсутнє.');";
                  html+="}else{";
                    html+="alert(`Помилка при отриманні ID: ${error}`);";
                  html+="}";
                html+="});";
            html+="} else{";
            html+="}";
          html+="} else{";
            html+="alert(\"Токен Telegram бота неправильний.\");";
          html+="}";
        html+="}";
        html+="function generateDisplayModes(){";
          html+="let binaryString='';";
          html+="for(let i=0;i<=6;i++){";
            html+="const checkbox=document.getElementById('display-mode-'+i);";
            html+="binaryString+=checkbox.checked?'1':'0';";
          html+="}";
          html+="document.getElementById('display-modes').value=binaryString;";
        html+="}";
        html+="timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone;";
        html+="utc=(new Date().toLocaleTimeString('en',{timeZoneName:'short'})).split(' ')[2].split('GMT')[1];";
        html+="document.getElementById('utc').textContent=`UTC зсув (у ${timeZone} ${utc})`;";
  }
        html+="function restart(){";
          html+="event.preventDefault();";
          html+="window.location.href='/restart';";
        html+="}";
        html+="function resetSettings(){";
          html+="event.preventDefault();";
          html+="let text='Ви впевнені, що хочете очистити всі налаштування? Ця дія видалить всі збережені налаштування і значення!\\nДля підтвердження, натисніть \"ОК\". Якщо ви не бажаєте очищувати налаштування, натисніть \"Скасувати\".';";
          html+="if(confirm(text)==true){";
            html+="window.location.href='/reset';";
          html+="}";
        html+="}";
      html+="</script>";
    html+="</body>";
  html+="</html>";

  return html;
}